name: Markdown Link Checker

on:
  pull_request:
    branches:
      - master

jobs:
  MarkdownLinkCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
